variables:
  PROJECT_PATH: "/var/www/delete-this/testing-three/testing-three-dotnet-api"

stages:
  - deploy
  - start

deploy-job:
  stage: deploy
  before_script:
    - mkdir -p "$PROJECT_PATH"
  script:
    - sudo find "$PROJECT_PATH" -mindepth 1 -maxdepth 1 ! -name ".env" -exec rm -rf {} + # DELETE ALL FILES FIRST EXCEPT LOGS FOLDER
    - sudo cp -r * "$PROJECT_PATH" # COPY ALL FILES FROM CURRENT GITLAB DIRECTORY TO A SPECIFIC PROJECT PATH
  only:
    - master
  tags:
    - docker

start-job:
  stage: start
  script:
    - cd "$PROJECT_PATH"
    - docker-compose build --no-cache
    - docker-compose up -d --remove-orphans # host
  only:
    - master
  tags:
    - docker